#imagen base de Java 21 proporcionada por AWS Lambda
FROM public.ecr.aws/lambda/java:21

# Copiar el archivo JAR de tu aplicación Spring Boot al contenedor
COPY target/FriendlySpots-0.0.1-SNAPSHOT.jar /app/FriendlySpots.jar

# Exponer el puerto en el que la aplicación escucha
EXPOSE 8080

# Comando para ejecutar la aplicación Spring Boot
CMD ["java", "-jar", "/app/FriendlySpots.jar"]
